# Generated by Django 3.2.6 on 2025-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=10)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('light', models.IntegerField()),
                ('snd', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'sensors',
            },
        ),
    ]
