# Generated by Django 3.2.6 on 2025-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hum',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='light',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='loc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='snd',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
