# Generated by Django 3.2.6 on 2025-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='light',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='snd',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
