# Generated by Django 3.2.6 on 2025-06-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('desription', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
