# Generated by Django 3.2.6 on 2025-07-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-date_created'], 'verbose_name': 'Sensor Data', 'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='light',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='snd',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
