# Generated by Django 3.2.6 on 2025-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=50)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light', models.IntegerField()),
                ('snd', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
